### ISSUE TITLE
Returning a status code in the save_and_shutdown function

### ISSUE THREAD

**Issue by ofir-petrushka** [lukecyca/travis-docker-example#2]
How about returning a status code in the save_and_shutdown function
https://github.com/lukecyca/travis-docker-example/blob/master/uml.sh#L9

I am automating docker build tests here:
https://github.com/rounds/10M-Docker-Images/tree/Ofir/git_client

**Comment by lukecyca** [comment]
Sounds good. I'd happily merge a pull request for this.

**Comment by ofir-petrushka** [comment]
This is what I am using, don't know if we can make it more elegant or it's good enough. 
https://github.com/lukecyca/travis-docker-example/pull/4

Also thanks for this repo it's a game changer for me!

**Comment by lukecyca** [comment]
Thanks!
